import { Project } from "@/types";
import { existsSync } from "fs";

export const projects: Project[] = [
  {
    title: "Colorado Avalanche Information Center (CAIC)",
    slug: "caic",
    description: (
      <span>
        Interactive avalanche forecasts & reports with graphics, maps, data
        tables, and complex forms. Winner of a{" "}
        <a href="https://we-awards.com/winner/colorado-avalanche-information-center/">
          Web Excellence Award
        </a>
      </span>
    ),
    imageUrl: "/caic.webp",
    url: "https://avalanche.state.co.us",
    tags: ["react", "typescript", "google maps", "CI/CD"],
  },
  {
    title: "Inventedle",
    slug: "inventedle",
    url: "https://inventedle.com",
    description:
      "The inventurous daily trivia game. Guess the year of the invention to win. Track your stats, compete with friends, and more!",
    imageUrl: "/inventedle.webp",
    tags: ["next.js", "typescript", "tailwind", "hosting", "CI/CD", "auth"],
  },
  {
    title: "combinator",
    slug: "combinator",
    url: "https://mtgcombinator.com",
    description:
      "Paste in a link to your Magic: The Gathering deck & immediately get an overview of what combos, loops, and shenanigans are inside. Also suggests combos that only require a single extra card",
    imageUrl: "/combinator.webp",
    tags: [
      "python",
      "fastapi",
      "pandas",
      "typescript",
      "react",
      "analytics",
      "hosting",
      "docker",
    ],
    sourceUrl: "https://github.com/naught0/combinator",
  },
  {
    title: "migr8",
    slug: "migr8",
    description:
      "A production web app used by Recharge customers to migrate data from their old system to ours. Designed and developed from the ground up by yours truly",
    url: "https://getrecharge.com",
    imageUrl: "/migr8.webp",
    tags: [
      "python",
      "SQL",
      "typescript",
      "react",
      "redis",
      "hosting",
      "system design",
      "security",
    ],
  },
  {
    title: "asyncurban",
    url: "https://asyncurban.readthedocs.io",
    sourceUrl: "https://github.com/naught0/asyncurban",
    slug: "asyncurban",
    description: (
      <span>
        An asynchronous python wrapper around the UrbanDictionary API.{" "}
        <strong>Over 1 million downloads!</strong>
      </span>
    ),
    imageUrl: "/asyncurban.webp",
    tags: ["python", "async", "API", "documentation", "package distribution"],
  },
  {
    title: "slacker_news",
    slug: "slackernews",
    url: "https://news.jamese.dev",
    description: (
      <span>
        A mobile-responsive frontend for{" "}
        <a href="https://news.ycombinator.com" target="_blank">
          Hacker News
        </a>{" "}
        with collapsible comments and crucially, dark mode
      </span>
    ),
    sourceUrl: "https://github.com/naught0/slackernews",
    imageUrl: "/slackernews.webp",
    tags: ["next.js", "typescript", "vercel", "SSR"],
  },
  {
    title: "jamese.dev",
    slug: "jamese-dev",
    description: "My personal website displaying some of my projects & skills",
    imageUrl: "/jamese-dev.webp",
    tags: ["typescript", "next.js", "tailwind", "hosting", "SSG"],
    sourceUrl: "https://github.com/naught0/naught0.github.io",
  },
  {
    title: "qtbot",
    slug: "qtbot",
    url: "https://github.com/naught0/qtbot",
    sourceUrl: "https://github.com/naught0/qtbot",
    description:
      "My personal, multifarious bot for Discord with over 70 commands",
    imageUrl: "/qtbot.webp",
    tags: ["python", "scraping", "API", "SQL", "redis"],
  },
  {
    title: "LogMeIn Log Analyzer",
    slug: "logmein-log-analyzer",
    url: "https://github.com/Naught0/LogMeIn-Log-Analyzer",
    sourceUrl: "https://github.com/Naught0/LogMeIn-Log-Analyzer",
    description:
      "A tool to analyze, parse, & filter various log files generated by LogMeIn applications. Created to accelerate my L2 tech support team",
    imageUrl: "/logmein-log-analyzer.webp",
    tags: ["C#", "desktop app", "visual studio"],
  },
  {
    title: "Clapback",
    url: "https://jamese.dev/clapback",
    sourceUrl: "https://github.com/naught0/clapback",
    slug: "clapback",
    description:
      "The ultimate website for the refined 21st century conversationalist. You can insert an emoji between each word you type or generate a moCkINg SpoNGeBob mEMe – the possibilities are endless",
    imageUrl: "/clapback.webp",
    tags: ["HTML", "CSS", "javascript", "jquery"],
  },
].map((proj) => ({
  ...proj,
  hasBlog: existsSync(`./data/posts/${proj.slug}.md`),
}));
