import mtgCombinator from "../Images/mtgCombinator.png";
import qtbot from "../Images/qtbot.png";
import asyncurban from "../Images/asyncurban.png";
import personalSite from "../Images/personalSite.png";
import rechargeMigr8 from "../Images/rechargeMigr8.png";

export interface Project {
  title: string;
  url?: string;
  description: string;
  imageUrl: string;
  tags: string[];
}
export const projects: Project[] = [
  {
    title: "combinator",
    url: "https://mtbcombinator.com",
    description:
      "Paste in your Magic: The Gathering deck & immediately get an overview of what combos, loops, and shenanigans are inside",
    imageUrl: mtgCombinator,
    tags: [
      "python",
      "flask",
      "pandas",
      "typescript",
      "react",
      "webhosting",
      "google cloud run",
      "docker",
    ],
  },
  {
    title: "migr8",
    url: "",
    description:
      "An internal web app that acts as an ETL from competitor APIs to our platform. Solo designed and developed from the ground up in 3 months",
    imageUrl: rechargeMigr8,
    tags: ["python", "asyncio", "flask", "SQL", "typescript", "react", "redis", "hosting", "GCP", "VPS", "system design", "parallelization"],
  },
  {
    title: "qtbot",
    url: "https://github.com/naught0/qtbot",
    description: "My personal, multifarious bot for Discord",
    imageUrl: qtbot,
    tags: ["python", "requests", "NLTK", "web-scraping", "VPS"],
  },
  {
    title: "asyncurban",
    url: "https://github.com/naught0/asyncurban",
    description:
      "An asynchronous python wrapper around the UrbanDictionary API. Used by over >7.6k projects.",
    imageUrl: asyncurban,
    tags: [
      "python",
      "asyncio",
      "REST API",
      "documentation",
      "sphinx",
      "package distribution",
    ],
  },
  {
    title: "LogMeIn Log Analyzer",
    url: "https://github.com/Naught0/LogMeIn-Log-Analyzer",
    description:
      "A tool made for work to analyze, parse, & filter various log files generated by LogMeIn applications",
    imageUrl:
      "https://camo.githubusercontent.com/034ab39dab23766299d7b8376c3eae4e05a0f40cf734258aa7bffcf165ccfe94/68747470733a2f2f692e696d6775722e636f6d2f537a36504650342e706e67",
    tags: [
      "C#",
      "winforms",
      "desktop app",
      "visual studio",
      "text parsing",
      "version control",
    ],
  },
  {
    title: "This site :)",
    url: "https://naught0.github.io",
    description: "My personal website displaying some of my projects & skills",
    imageUrl: personalSite,
    tags: ["typescript", "react", "tailwind.css"],
  },
];
