import mtgCombinator from "../Images/mtgCombinator.png";
import qtbot from "../Images/qtbot.png";
import asyncurban from "../Images/asyncurban.png";
import personalSite from "../Images/personalSite.png";
import rechargeMigr8 from "../Images/rechargeMigr8.png";
import avalanche from "../Images/avalanche.state.co.us.png";

export interface Project {
  title: string;
  url?: string;
  description: string;
  imageUrl: string;
  tags: string[];
}
export const projects: Project[] = [
  {
    title: "combinator",
    url: "https://mtbcombinator.com",
    description:
      "Paste in your Magic: The Gathering deck & immediately get an overview of what combos, loops, and shenanigans are inside",
    imageUrl: mtgCombinator,
    tags: [
      "python",
      "flask",
      "pandas",
      "typescript",
      "react",
      "web hosting",
      "google cloud run",
      "docker",
    ],
  },
  {
    title: "migr8",
    description:
      "An internal web app that acts as an ETL from competitor APIs to our platform. Solo designed and developed from the ground up in 3 months",
    imageUrl: rechargeMigr8,
    tags: [
      "python",
      "asyncio",
      "flask",
      "SQL",
      "typescript",
      "react",
      "redis",
      "hosting",
      "GCP",
      "VPS",
      "system design",
      "parallelization",
      "user roles",
      "security",
    ],
  },
  {
    title: "Colorado Avalanche Information Center (CAIC)",
    description:
      "Interactive Map, tables, & misc. other components for the CAIC website to forecast, warn, & catalog avalanches in Colorado. Live Q4 2022",
    imageUrl: avalanche,
    url: "https://avalanche.state.co.us",
    tags: [
      "react.js",
      "google maps",
      "google places",
      "caching",
      "CI/CD",
      "agile",
      "design implementation",
    ],
  },
  {
    title: "this site :)",
    url: "https://naught0.github.io",
    description: "My personal website displaying some of my projects & skills",
    imageUrl: personalSite,
    tags: [
      "typescript",
      "react",
      "tailwind.css",
      "deployment",
      "web hosting",
      "github pages",
    ],
  },
  {
    title: "asyncurban",
    url: "https://github.com/naught0/asyncurban",
    description:
      "An asynchronous python wrapper around the UrbanDictionary API. Used by over >7.6k projects.",
    imageUrl: asyncurban,
    tags: [
      "python",
      "asyncio",
      "REST API",
      "documentation",
      "sphinx",
      "package distribution",
    ],
  },
  {
    title: "qtbot",
    url: "https://github.com/naught0/qtbot",
    description: "My personal, multifarious bot for Discord",
    imageUrl: qtbot,
    tags: ["python", "requests", "NLTK", "web-scraping", "APIs", "SQL", "redis", "caching", "VPS"],
  },
  {
    title: "LogMeIn Log Analyzer",
    url: "https://github.com/Naught0/LogMeIn-Log-Analyzer",
    description:
      "A tool made for work to analyze, parse, & filter various log files generated by LogMeIn applications",
    imageUrl:
      "https://camo.githubusercontent.com/034ab39dab23766299d7b8376c3eae4e05a0f40cf734258aa7bffcf165ccfe94/68747470733a2f2f692e696d6775722e636f6d2f537a36504650342e706e67",
    tags: [
      "C#",
      "winforms",
      "desktop app",
      "visual studio",
      "text parsing",
      "version control",
    ],
  },
];
